aggregation: krum_pseudo
attack_client: Backdoor
attack_epochs: 10
attack_server: null
backdoor_config: configs/backdoor_tasks/mnist_params_pattern.yaml
backdoor_type: 9-pixel
batch_size: 32
clients_per_round: 10
cluster: false
cluster_stored_rounds: 10
cuda: true
data_sampler: uniform
data_sampler_args:
- 5
- 42
dataset_name: fashion-mnist
defense: null
epochs: 10
experiment_prefix: RANDOM-TESTING-CLIENT2SERVER #SCORED-USING-CLIENT2CLIENT-AND-CLIENT2SERVER # Final
run_prefix: ""
mal_boost: 1
mal_clients_per_round: 2
net_name: FashionMNISTCNN
num_clients: 100
num_mal_clients: 25
offload_stategy: deadline
output_location: output
pert_strength: 0.2
regular_weight: 0.4
rounds: 40 #80
selection_method: random
single_machine: true
tensor_board_active: true
use_wandb: true
wait_for_clients: true
############################
# for any new param added here, it must also be add to ./fltk/util/config/config.py
pseudo_lr: 0.01 # best 0.01
pseudo_momentum: 0.99 # best 0.99
pseudo_iterations: 100 # best 100
#############################
